name: PySpark CI Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install pyspark==3.5.0
        pip install setuptools

    - name: Check PySpark Script Syntax
      run: python -m py_compile consumer_spark.py

    - name: Check Dashboard Script Syntax
      run: python -m py_compile dashboard.py